on:
  pull_request:
    branches:
      - master

name: Check and Lint

jobs:
  python:
    name: Python Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build Container
        run: docker build -t assassyn-dev .
      - name: Run Python Lint
        run: docker run --rm -v ${{ github.workspace }}:/app --user $(id -u):$(id -g) assassyn-dev pylint --rcfile python/.pylintrc python/assassyn
