on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

env:
  VERILATOR_VERSION: v5.026

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: docker build -t assassyn-dev .
      - name: Python Frontend Unit Tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/app --user $(id -u):$(id -g) assassyn-dev bash -c "
            pytest -n 8 python/unit-tests;
            python3 examples/systolic-array/systolic_array.py;
            python3 examples/systolic-array/memory_systolic_array.py;
            python3 examples/minor-cpu/src/main.py;
            python3 examples/minor-cpu/src/br_pre_main.py;
            python3 examples/priority-queue/main.py;
          "
